# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Karlobrien
tagline:             ''
description:         'Overview of personal projects, technical lists and useful technology links'
url:                 http://karlobrien.github.io/
baseurl:             ""
paginate:            5
excerpt_separator:   <!--more-->

# About/contact
author:
  name:              Karl O Brien
  url:               https://karlobrien.github.io
  email:             karlobrien@gmail.com

# Custom vars
version:             1.0.0
