# Site settings
title: Karl O'Brien
email: karlobrien@gmail.com
description: Descriptions and links to software projects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://karlobrien.ie" # the base hostname & protocol for your site
twitter_username: jumpercake
github_username:  karlobrien
linkedin_username: karl-o-brien/6/aa5/48

# Build settings
markdown: kramdown
